### ISSUE TITLE
bug: orders index page shows on the buyer column the buyer of the first order

### ISSUE THREAD

**Issue by ordago** [LeanAdmin/ecom-example#3]
https://demo.lean-admin.dev/admin/orders

![Oj1dWDuKua](https://user-images.githubusercontent.com/6376814/101911448-45713380-3bb8-11eb-8c0f-4977fc2b0673.gif)

**Comment by stancl** [comment]
Fixed! This bug was briefly introduced and quickly fixed in dev-master. I redeployed the demo and it works now 👍🏻
